# Name:harish Panpaliya
#Branh:CS_AI
#Division: D Batch-3
#Roll no:52
#PRN no: 12412173
#Date: 08/01/2026
#Time: 4:20

Kaggle dataset link:
 https://www.kaggle.com/datasets/lashagoch/life-expectancy-who-updated

Perform the following operations using Python on suitable data sets:

#1.Read data from different formats (like csv, xls)
#2.Find Shape of Data
#3.Find Missing Values
#4.Find data type of each column
#5.Finding out Zero's
#6.Indexing and selecting data, sort data,
#7.Describe attributes of data, checking data types of each column,
#8.counting unique values of data, format of each column, converting variable data type (e.g. from long to short, vice versa)

# Imported Pandas and numpy

In [ ]:

import pandas as pd
import numpy as np

# Read The CSv and Xlsx file and print them

In [ ]:
df=pd.read_csv('dataset.csv')

In [ ]:
print(df)

        Country          Region  Year  Infant_deaths  Under_five_deaths  \
0       Turkiye     Middle East  2015           11.1               13.0
1         Spain  European Union  2015            2.7                3.3
2         India            Asia  2007           51.5               67.9
3        Guyana   South America  2006           32.8               40.5
4        Israel     Middle East  2012            3.4                4.3
...         ...             ...   ...            ...                ...
2859      Niger          Africa  2000           97.0              224.9
2860   Mongolia            Asia  2009           23.9               28.6
2861  Sri Lanka            Asia  2004           17.7               28.9
2862  Lithuania  European Union  2002            7.9                9.9
2863    Iceland  Rest of Europe  2011            2.1                2.6

      Adult_mortality  Alcohol_consumption  Hepatitis_B  Measles   BMI  ...  \
0            105.8240                1.320           97       65  27.8  ...
1             57.9025               10.350           97       94  26.0  ...
2            201.0765                1.570           60       35  21.2  ...
3            222.1965                5.680           93       74  25.3  ...
4             57.9510                2.890           97       89  27.0  ...
...               ...                  ...          ...      ...   ...  ...
2859         291.8240                0.092           72       64  20.8  ...
2860         235.2330                6.560           97       97  25.3  ...
2861         134.8950                1.560           62       95  21.9  ...
2862         204.0120               11.000           94       95  26.1  ...
2863          50.5745                6.840           88       90  26.1  ...

      Diphtheria  Incidents_HIV  GDP_per_capita  Population_mln  \
0             97           0.08           11006           78.53
1             97           0.09           25742           46.44
2             64           0.13            1076         1183.21
3             93           0.79            4146            0.75
4             94           0.08           33995            7.91
...          ...            ...             ...             ...
2859          34           0.49             399           11.33
2860          95           0.02            2515            2.67
2861          97           0.02            2130           19.39
2862          95           0.05            7424            3.44
2863          95           0.05           48934            0.32

      Thinness_ten_nineteen_years  Thinness_five_nine_years  Schooling  \
0                             4.9                       4.8        7.8
1                             0.6                       0.5        9.7
2                            27.1                      28.0        5.0
3                             5.7                       5.5        7.9
4                             1.2                       1.1       12.8
...                           ...                       ...        ...
2859                         12.8                      12.9        1.1
2860                          2.2                       2.3        9.1
2861                         15.4                      15.5       10.3
2862                          3.3                       3.3       11.1
2863                          0.9                       0.9       11.0

      Economy_status_Developed  Economy_status_Developing  Life_expectancy
0                            0                          1             76.5
1                            1                          0             82.8
2                            0                          1             65.4
3                            0                          1             67.0
4                            1                          0             81.7
...                        ...                        ...              ...
2859                         0                          1             49.9
2860                         0                          1             66.9
2861                         0                          1             74.3
2862                         1                          0             71.8
2863                         1                          0             82.4

[2864 rows x 21 columns]

In [ ]:
df

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
0,Turkiye,Middle East,2015,11.1,13.0,105.8240,1.320,97,65,27.8,...,97,0.08,11006,78.53,4.9,4.8,7.8,0,1,76.5
1,Spain,European Union,2015,2.7,3.3,57.9025,10.350,97,94,26.0,...,97,0.09,25742,46.44,0.6,0.5,9.7,1,0,82.8
2,India,Asia,2007,51.5,67.9,201.0765,1.570,60,35,21.2,...,64,0.13,1076,1183.21,27.1,28.0,5.0,0,1,65.4
3,Guyana,South America,2006,32.8,40.5,222.1965,5.680,93,74,25.3,...,93,0.79,4146,0.75,5.7,5.5,7.9,0,1,67.0
4,Israel,Middle East,2012,3.4,4.3,57.9510,2.890,97,89,27.0,...,94,0.08,33995,7.91,1.2,1.1,12.8,1,0,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2859,Niger,Africa,2000,97.0,224.9,291.8240,0.092,72,64,20.8,...,34,0.49,399,11.33,12.8,12.9,1.1,0,1,49.9
2860,Mongolia,Asia,2009,23.9,28.6,235.2330,6.560,97,97,25.3,...,95,0.02,2515,2.67,2.2,2.3,9.1,0,1,66.9
2861,Sri Lanka,Asia,2004,17.7,28.9,134.8950,1.560,62,95,21.9,...,97,0.02,2130,19.39,15.4,15.5,10.3,0,1,74.3
2862,Lithuania,European Union,2002,7.9,9.9,204.0120,11.000,94,95,26.1,...,95,0.05,7424,3.44,3.3,3.3,11.1,1,0,71.8
2863,Iceland,Rest of Europe,2011,2.1,2.6,50.5745,6.840,88,90,26.1,...,95,0.05,48934,0.32,0.9,0.9,11.0,1,0,82.4

In [ ]:
df_xl=pd.read_excel('dataset2.xlsx')

In [ ]:
print(df_xl)

        Country          Region  Year  Infant_deaths  Under_five_deaths  \
0       Turkiye     Middle East  2015           11.1               13.0
1         Spain  European Union  2015            2.7                3.3
2         India            Asia  2007           51.5               67.9
3        Guyana   South America  2006           32.8               40.5
4        Israel     Middle East  2012            3.4                4.3
...         ...             ...   ...            ...                ...
2859      Niger          Africa  2000           97.0              224.9
2860   Mongolia            Asia  2009           23.9               28.6
2861  Sri Lanka            Asia  2004           17.7               28.9
2862  Lithuania  European Union  2002            7.9                9.9
2863    Iceland  Rest of Europe  2011            2.1                2.6

      Adult_mortality  Alcohol_consumption  Hepatitis_B  Measles   BMI  ...  \
0            105.8240                1.320           97       65  27.8  ...
1             57.9025               10.350           97       94  26.0  ...
2            201.0765                1.570           60       35  21.2  ...
3            222.1965                5.680           93       74  25.3  ...
4             57.9510                2.890           97       89  27.0  ...
...               ...                  ...          ...      ...   ...  ...
2859         291.8240                0.092           72       64  20.8  ...
2860         235.2330                6.560           97       97  25.3  ...
2861         134.8950                1.560           62       95  21.9  ...
2862         204.0120               11.000           94       95  26.1  ...
2863          50.5745                6.840           88       90  26.1  ...

      Diphtheria  Incidents_HIV  GDP_per_capita  Population_mln  \
0             97           0.08           11006           78.53
1             97           0.09           25742           46.44
2             64           0.13            1076         1183.21
3             93           0.79            4146            0.75
4             94           0.08           33995            7.91
...          ...            ...             ...             ...
2859          34           0.49             399           11.33
2860          95           0.02            2515            2.67
2861          97           0.02            2130           19.39
2862          95           0.05            7424            3.44
2863          95           0.05           48934            0.32

      Thinness_ten_nineteen_years  Thinness_five_nine_years  Schooling  \
0                             4.9                       4.8        7.8
1                             0.6                       0.5        9.7
2                            27.1                      28.0        5.0
3                             5.7                       5.5        7.9
4                             1.2                       1.1       12.8
...                           ...                       ...        ...
2859                         12.8                      12.9        1.1
2860                          2.2                       2.3        9.1
2861                         15.4                      15.5       10.3
2862                          3.3                       3.3       11.1
2863                          0.9                       0.9       11.0

      Economy_status_Developed  Economy_status_Developing  Life_expectancy
0                            0                          1             76.5
1                            1                          0             82.8
2                            0                          1             65.4
3                            0                          1             67.0
4                            1                          0             81.7
...                        ...                        ...              ...
2859                         0                          1             49.9
2860                         0                          1             66.9
2861                         0                          1             74.3
2862                         1                          0             71.8
2863                         1                          0             82.4

[2864 rows x 21 columns]

In [ ]:
df_xl

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
0,Turkiye,Middle East,2015,11.1,13.0,105.8240,1.320,97,65,27.8,...,97,0.08,11006,78.53,4.9,4.8,7.8,0,1,76.5
1,Spain,European Union,2015,2.7,3.3,57.9025,10.350,97,94,26.0,...,97,0.09,25742,46.44,0.6,0.5,9.7,1,0,82.8
2,India,Asia,2007,51.5,67.9,201.0765,1.570,60,35,21.2,...,64,0.13,1076,1183.21,27.1,28.0,5.0,0,1,65.4
3,Guyana,South America,2006,32.8,40.5,222.1965,5.680,93,74,25.3,...,93,0.79,4146,0.75,5.7,5.5,7.9,0,1,67.0
4,Israel,Middle East,2012,3.4,4.3,57.9510,2.890,97,89,27.0,...,94,0.08,33995,7.91,1.2,1.1,12.8,1,0,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2859,Niger,Africa,2000,97.0,224.9,291.8240,0.092,72,64,20.8,...,34,0.49,399,11.33,12.8,12.9,1.1,0,1,49.9
2860,Mongolia,Asia,2009,23.9,28.6,235.2330,6.560,97,97,25.3,...,95,0.02,2515,2.67,2.2,2.3,9.1,0,1,66.9
2861,Sri Lanka,Asia,2004,17.7,28.9,134.8950,1.560,62,95,21.9,...,97,0.02,2130,19.39,15.4,15.5,10.3,0,1,74.3
2862,Lithuania,European Union,2002,7.9,9.9,204.0120,11.000,94,95,26.1,...,95,0.05,7424,3.44,3.3,3.3,11.1,1,0,71.8
2863,Iceland,Rest of Europe,2011,2.1,2.6,50.5745,6.840,88,90,26.1,...,95,0.05,48934,0.32,0.9,0.9,11.0,1,0,82.4

 # datatype of data in each column

In [ ]:
df.dtypes

Country                         object
Region                          object
Year                             int64
Infant_deaths                  float64
Under_five_deaths              float64
Adult_mortality                float64
Alcohol_consumption            float64
Hepatitis_B                      int64
Measles                          int64
BMI                            float64
Polio                            int64
Diphtheria                       int64
Incidents_HIV                  float64
GDP_per_capita                   int64
Population_mln                 float64
Thinness_ten_nineteen_years    float64
Thinness_five_nine_years       float64
Schooling                      float64
Economy_status_Developed         int64
Economy_status_Developing        int64
Life_expectancy                float64
dtype: object

# shape of dataset

In [ ]:
df.shape

(2864, 21)

# Reading head and Tail of the data

In [ ]:
df.head()

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
0,Turkiye,Middle East,2015,11.1,13.0,105.8240,1.32,97,65,27.8,...,97,0.08,11006,78.53,4.9,4.8,7.8,0,1,76.5
1,Spain,European Union,2015,2.7,3.3,57.9025,10.35,97,94,26.0,...,97,0.09,25742,46.44,0.6,0.5,9.7,1,0,82.8
2,India,Asia,2007,51.5,67.9,201.0765,1.57,60,35,21.2,...,64,0.13,1076,1183.21,27.1,28.0,5.0,0,1,65.4
3,Guyana,South America,2006,32.8,40.5,222.1965,5.68,93,74,25.3,...,93,0.79,4146,0.75,5.7,5.5,7.9,0,1,67.0
4,Israel,Middle East,2012,3.4,4.3,57.9510,2.89,97,89,27.0,...,94,0.08,33995,7.91,1.2,1.1,12.8,1,0,81.7

In [ ]:
df.tail(3)

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
2861,Sri Lanka,Asia,2004,17.7,28.9,134.8950,1.56,62,95,21.9,...,97,0.02,2130,19.39,15.4,15.5,10.3,0,1,74.3
2862,Lithuania,European Union,2002,7.9,9.9,204.0120,11.00,94,95,26.1,...,95,0.05,7424,3.44,3.3,3.3,11.1,1,0,71.8
2863,Iceland,Rest of Europe,2011,2.1,2.6,50.5745,6.84,88,90,26.1,...,95,0.05,48934,0.32,0.9,0.9,11.0,1,0,82.4

In [ ]:
df.index

RangeIndex(start=0, stop=2864, step=1)

In [ ]:
df.describe()

,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
count,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000,2864.000000
mean,2007.500000,30.363792,42.938268,192.251775,4.820882,84.292598,77.344972,25.032926,86.499651,86.271648,0.894288,11540.924930,36.675915,4.865852,4.899825,7.632123,0.206704,0.793296,68.856075
std,4.610577,27.538117,44.569974,114.910281,3.981949,15.995511,18.659693,2.193905,15.080365,15.534225,2.381389,16934.788931,136.485867,4.438234,4.525217,3.171556,0.405012,0.405012,9.405608
min,2000.000000,1.800000,2.300000,49.384000,0.000000,12.000000,10.000000,19.800000,8.000000,16.000000,0.010000,148.000000,0.080000,0.100000,0.100000,1.100000,0.000000,0.000000,39.400000
25%,2003.750000,8.100000,9.675000,106.910250,1.200000,78.000000,64.000000,23.200000,81.000000,81.000000,0.080000,1415.750000,2.097500,1.600000,1.600000,5.100000,0.000000,1.000000,62.700000
50%,2007.500000,19.600000,23.100000,163.841500,4.020000,89.000000,83.000000,25.500000,93.000000,93.000000,0.150000,4217.000000,7.850000,3.300000,3.400000,7.800000,0.000000,1.000000,71.400000
75%,2011.250000,47.350000,66.000000,246.791375,7.777500,96.000000,93.000000,26.400000,97.000000,97.000000,0.460000,12557.000000,23.687500,7.200000,7.300000,10.300000,0.000000,1.000000,75.400000
max,2015.000000,138.100000,224.900000,719.360500,17.870000,99.000000,99.000000,32.100000,99.000000,99.000000,21.680000,112418.000000,1379.860000,27.700000,28.600000,14.100000,1.000000,1.000000,83.800000

#sort by year

In [ ]:
df.sort_values(by="Year")

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,...,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
744,Eritrea,Africa,2000,56.1,85.2,370.4550,0.88,87,88,20.1,...,81,0.70,828,2.29,1.2,1.1,3.7,0,1,55.3
7,Hungary,European Union,2000,8.7,10.1,192.9690,12.23,88,99,25.9,...,99,0.08,8971,10.21,2.3,2.3,10.2,1,0,71.2
1789,North Macedonia,Rest of Europe,2000,14.3,16.0,123.0060,4.49,72,97,25.6,...,95,0.08,3283,2.03,2.8,2.8,6.5,0,1,72.9
2402,Belgium,European Union,2000,4.8,5.8,99.6000,11.21,60,78,25.5,...,95,0.08,35675,10.25,0.8,0.8,10.0,1,0,77.7
2823,Czechia,European Union,2000,4.5,5.5,124.3800,13.90,92,98,26.5,...,98,0.08,12312,10.26,2.3,2.3,10.6,1,0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,Spain,European Union,2015,2.7,3.3,57.9025,10.35,97,94,26.0,...,97,0.09,25742,46.44,0.6,0.5,9.7,1,0,82.8
6,Russian Federation,Rest of Europe,2015,6.6,8.2,223.0000,8.06,97,97,26.2,...,97,0.08,9313,144.10,2.3,2.3,12.0,0,1,71.2
2848,Bahrain,Middle East,2015,6.5,7.6,66.6840,1.53,98,99,24.8,...,98,0.05,22634,1.37,6.2,6.1,9.3,0,1,76.8
27,Cameroon,Africa,2015,57.0,88.0,340.1265,4.55,84,64,24.3,...,84,1.12,1383,23.30,5.6,5.5,6.1,0,1,57.6
2820,"Venezuela, RB",South America,2015,16.4,19.1,141.5540,6.21,87,83,26.7,...,87,0.40,17318,30.08,1.6,1.5,10.1,0,1,72.6

# sort by axis

In [ ]:
df.sort_index(axis=1)

,Adult_mortality,Alcohol_consumption,BMI,Country,Diphtheria,Economy_status_Developed,Economy_status_Developing,GDP_per_capita,Hepatitis_B,Incidents_HIV,...,Life_expectancy,Measles,Polio,Population_mln,Region,Schooling,Thinness_five_nine_years,Thinness_ten_nineteen_years,Under_five_deaths,Year
0,105.8240,1.320,27.8,Turkiye,97,0,1,11006,97,0.08,...,76.5,65,97,78.53,Middle East,7.8,4.8,4.9,13.0,2015
1,57.9025,10.350,26.0,Spain,97,1,0,25742,97,0.09,...,82.8,94,97,46.44,European Union,9.7,0.5,0.6,3.3,2015
2,201.0765,1.570,21.2,India,64,0,1,1076,60,0.13,...,65.4,35,67,1183.21,Asia,5.0,28.0,27.1,67.9,2007
3,222.1965,5.680,25.3,Guyana,93,0,1,4146,93,0.79,...,67.0,74,92,0.75,South America,7.9,5.5,5.7,40.5,2006
4,57.9510,2.890,27.0,Israel,94,1,0,33995,97,0.08,...,81.7,89,94,7.91,Middle East,12.8,1.1,1.2,4.3,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2859,291.8240,0.092,20.8,Niger,34,0,1,399,72,0.49,...,49.9,64,41,11.33,Africa,1.1,12.9,12.8,224.9,2000
2860,235.2330,6.560,25.3,Mongolia,95,0,1,2515,97,0.02,...,66.9,97,96,2.67,Asia,9.1,2.3,2.2,28.6,2009
2861,134.8950,1.560,21.9,Sri Lanka,97,0,1,2130,62,0.02,...,74.3,95,97,19.39,Asia,10.3,15.5,15.4,28.9,2004
2862,204.0120,11.000,26.1,Lithuania,95,1,0,7424,94,0.05,...,71.8,95,97,3.44,European Union,11.1,3.3,3.3,9.9,2002
2863,50.5745,6.840,26.1,Iceland,95,1,0,48934,88,0.05,...,82.4,90,95,0.32,Rest of Europe,11.0,0.9,0.9,2.6,2011

# Created own data and dataframe

In [ ]:
from numpy import nan
import pandas as pd
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,10,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
df_f

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
1     Ram   19      M   80.0         0.0
2  shital   20      F   50.0         1.0
3    Riya   21      F   40.0         1.0
4      OM   18      M    NaN         0.0
5   Rohan   18      M   75.0         0.0

# datatypes of data in dataframe

In [ ]:
from numpy import nan
import pandas as pd
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,nan,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
df_f.dtypes

Name           object
Age             int64
Gender         object
Marks         float64
Internship    float64
dtype: object

# Index of row with marks=NULL

In [ ]:
from numpy import nan
import pandas as pd
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,nan,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
nan_indices = df_f[df_f['Marks'].isna()].index.tolist()
nan_indices

[4]

# Drop rows which have null value --> temporary

In [ ]:
from numpy import nan
import pandas as pd
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,nan,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
df_f.dropna(how="any")

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
1     Ram   19      M   80.0         0.0
2  shital   20      F   50.0         1.0
3    Riya   21      F   40.0         1.0
5   Rohan   18      M   75.0         0.0

# using ioc,iloc,at and isin

In [ ]:
# df_f.loc("Age",)=[20,22,25,18,18,30]
# The correct syntax
df_f.loc[ :,"Age"] = [20, 22, 25, 18,30,18]
df_f

     Name  Age Gender  Marks  Internship
0  Harish   20      M   90.0         1.0
1     Ram   22      M   80.0         0.0
2  shital   25      F   50.0         1.0
3    Riya   18      F   40.0         1.0
4      OM   30      M    NaN         0.0
5   Rohan   18      M   75.0         0.0

In [ ]:
df_f.iloc[[0, 2, 5], [1, 3]]

   Age  Marks
0   20   90.0
2   25   50.0
5   18   75.0

In [ ]:

mark = df_f.at[5, 'Marks']
print(mark)

75.0

In [ ]:
df_f[df_f["Name"].isin(["Harish","Ram","shital","Riya","OM","Rohan"])]

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
1     Ram   19      M   80.0         0.0
2  shital   20      F   50.0         1.0
3    Riya   21      F   40.0         1.0
4      OM   18      M    NaN         0.0
5   Rohan   18      M   75.0         0.0

In [ ]:
df_f["Name"].isin(["Harish","Ram","shital","Riya","OM","Rohan"])

0    True
1    True
2    True
3    True
4    True
5    True
Name: Name, dtype: bool

# calculated Average of marks excluding null

In [ ]:
from numpy import nan
import pandas as pd
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,nan,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
df_f.dropna(how="any")['Marks'].mean()

np.float64(67.0)

In [ ]:
average_marks = df_f['Marks'].mean()
average_marks

np.float64(67.0)

In [ ]:
c=avg=0
for ele in df_f['Marks']:
  if pd.notnull(ele):
     c=c+1
     avg=avg+ele
avg=avg/c
print(avg)

67.0

# Changed Male to 0 and Female to 1

In [ ]:
from numpy import nan
import pandas as pd
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,nan,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
df_f['Gender'].map({'M':0,'F':1,}).astype(float)

0    0.0
1    0.0
2    1.0
3    1.0
4    0.0
5    0.0
Name: Gender, dtype: float64

#user define function using agg

In [ ]:
# This returns the new Age column
df_f['Age'].agg(lambda x: x + 1)

/tmp/ipython-input-3236170448.py:2: FutureWarning: using <function <lambda> at 0x7ddaa66e96c0> in Series.agg cannot aggregate and has been deprecated. Use Series.transform to keep behavior unchanged.
  df_f['Age'].agg(lambda x: x + 1)

0    19
1    20
2    21
3    22
4    19
5    19
Name: Age, dtype: int64

# Sorted students who scored more than or equal to 80

In [ ]:
df_s=df_f[df_f['Marks']>=80].copy()
df_s

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
1     Ram   19      M   80.0         0.0

# Removed Age column

In [ ]:
df_f.drop('Age',axis=1, inplace=True)
df_f

     Name Gender  Marks  Internship
0  Harish      M   90.0         1.0
1     Ram      M   80.0         0.0
2  shital      F   50.0         1.0
3    Riya      F   40.0         1.0
4      OM      M    NaN         0.0
5   Rohan      M   75.0         0.0

# Slicing

In [ ]:
import pandas as pd
from numpy import nan
data={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Age':[18,19,20,21,18,18],
    'Gender':['M','M','F','F','M','M'],
    'Marks':[90,80,50,40,nan,75],
    'Internship':[1.0,0.0,1.0,1.0,0.0,0.0]
}
df_f=pd.DataFrame(data)
df_f.iloc[0:4]

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
1     Ram   19      M   80.0         0.0
2  shital   20      F   50.0         1.0
3    Riya   21      F   40.0         1.0

In [ ]:
df_f.sort_values(by='Name')

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
4      OM   18      M    NaN         0.0
1     Ram   19      M   80.0         0.0
3    Riya   21      F   40.0         1.0
5   Rohan   18      M   75.0         0.0
2  shital   20      F   50.0         1.0

In [ ]:
df_f.fillna(60.0)

     Name  Age Gender  Marks  Internship
0  Harish   18      M   90.0         1.0
1     Ram   19      M   80.0         0.0
2  shital   20      F   50.0         1.0
3    Riya   21      F   40.0         1.0
4      OM   18      M   60.0         0.0
5   Rohan   18      M   75.0         0.0

In [ ]:
data2={
    'Name':["Harish","Ram","shital","Riya","OM","Rohan"],
    'Pending_fee':[1,0,0,1,1,0],
    'Branch':['CSE','CSE_AI','AI_Ml','CSE','CSE','CSE'],
    'rating':[5,3,2,4,1,5]


}

In [ ]:
df_f=pd.DataFrame(data2)

In [ ]:
df_f["Branch"]

0       CSE
1    CSE_AI
2     AI_Ml
3       CSE
4       CSE
5       CSE
Name: Branch, dtype: object

In [ ]:
df_f.loc[:,["Name","Pending_fee"]]

     Name  Pending_fee
0  Harish            1
1     Ram            0
2  shital            0
3    Riya            1
4      OM            1
5   Rohan            0

In [ ]:
df_f.iloc[3]

Name           Riya
Pending_fee       1
Branch          CSE
rating            4
Name: 3, dtype: object

In [ ]:
s1 = pd.Series(
   [1, 2, 3, 4, 5, 6],
   index=pd.date_range("20260122", periods=6))
s1

2026-01-22    1
2026-01-23    2
2026-01-24    3
2026-01-25    4
2026-01-26    5
2026-01-27    6
Freq: D, dtype: int64